version: '3.8'
services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:80"
#    environment:
#      ASPNETCORE_ENVIRONMENT: Development
#      ConnectionStrings__Postgres: "Host=db;Port=5432;Database=daiminh;Username=user;Password=password"
#      Redis__Connection: "redis:6379"
#    depends_on:
#      - db
#      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: daiminh
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data: