services:
  postgresql:
    image: postgres:15 
    container_name: daiminh_postgresql 
    restart: unless-stopped
    environment:
      POSTGRES_USER: nguyenviethung
      POSTGRES_PASSWORD: 5v3LEO8ePNVVZLSa57h50Q
      POSTGRES_DB: daiminh_pg 
    ports:
      - "5432:5432"
    volumes:
      - postgresql-daiminh:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nguyenviethung -d daiminh_pg"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: daiminh_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-daiminh2:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    container_name: daiminh_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgresql-daiminh:         
    name: daiminh-postgresql-data
  sqlserver-daiminh:
    name: daiminh-sqlserver-data
  minio-daiminh2:
    name: daiminh2-minio-data
  redis-data:
    name: daiminh-redis-data

networks:
  app-network:
    name: daiminh2-network
    driver: bridge