version: '3.8'
services:
  daiminh-web:
    image: yourdockerhubusername/daiminh-web:latest
    container_name: daiminh-web
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - daiminh-network

networks:
  daiminh-network: